### ISSUE TITLE
display: block for SVG element

### ISSUE THREAD

**Issue by boystrange** [Beg-in/frow#37]
I'm not sure the display attribute for the SVG element should be block, as is set in _scaffolding.sass. As it is, it breaks the inline uses of svg, for example those resulting from MathJax rendering of math formulas. This problem can be fixed by overriding the attribute after loading frow, but I don't think it's ideal.

Thanks for the excellent framework.

**Comment by codysherman** [comment]
You're honestly right, I should and will revert that SVG rule to be more consistent. The catch is that this change would be considered a "breaking change" and would warrant bumping Frow up a major version. So I'll perhaps try to sneak in some other items from the to-do list.

In the immediate term, your override will at least let you move forward. Apologies for the bad rule, but thanks for using Frow!

**Comment by codysherman** [comment]
Sorry it took so darn long, but the change is now live!
https://github.com/Beg-in/frow/releases/tag/4.0.0
