### ISSUE TITLE
Sass is deprecating division with "/" and throws a lot of warnings

### ISSUE THREAD

**Issue by jasalguero** [Beg-in/frow#43]
```
⠦ building... [Package /assets/vendor.js]DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$grid-gutter-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

**Comment by jasalguero** [comment]
It's a small issue but quite annoying because it pollutes console a lot

**Comment by codysherman** [comment]
Thanks for the report! Will attempt to reproduce, I must be be on an older version of Sass.

**Comment by codysherman** [comment]
Solved in https://github.com/Beg-in/frow/pull/45

Will go out in the next minor release (hopefully today).

**Comment by codysherman** [comment]
This is now live on npm as version 3.3.3

https://github.com/Beg-in/frow/releases/tag/3.3.3
